### ISSUE TITLE
https://github.com/feribg/audiogetter/blob/master/audiogetter/src/main/java/com/github/feribg/audiogetter/tasks/download/VideoTask.java

### ISSUE THREAD

**Issue by teamco** [splanger/youtube2mp3#1]

**Comment by yurikroz** [comment]
I've checked the link. At the end, I wouldn't rely on this piece of code, because it is as old as the hills. The last commit was submitted 2 years ago while even the README states:

"This is a work in progress, currently it doesn't compile or run....
